// Code generated by the Encore 1.50.6 client generator. DO NOT EDIT.

// Disable eslint, jshint, and jslint for this file.
/* eslint-disable */
/* jshint ignore:start */
/*jslint-disable*/
import type { CookieWithOptions } from "encore.dev/api";

/**
 * BaseURL is the base URL for calling the Encore application's API.
 */
export type BaseURL = string

export const Local: BaseURL = "http://localhost:4000"

/**
 * Environment returns a BaseURL for calling the cloud environment with the given name.
 */
export function Environment(name: string): BaseURL {
    return `https://${name}-.encr.app`
}

/**
 * PreviewEnv returns a BaseURL for calling the preview environment with the given PR number.
 */
export function PreviewEnv(pr: number | string): BaseURL {
    return Environment(`pr${pr}`)
}

const BROWSER = typeof globalThis === "object" && ("window" in globalThis);

/**
 * Client is an API client for the  Encore application.
 */
export class Client {
    public readonly ai: ai.ServiceClient
    public readonly auth: auth.ServiceClient
    public readonly bookings: bookings.ServiceClient
    public readonly conversations: conversations.ServiceClient
    public readonly crm: crm.ServiceClient
    public readonly files: files.ServiceClient
    public readonly fleet: fleet.ServiceClient
    public readonly quotes: quotes.ServiceClient
    public readonly settings: settings.ServiceClient
    private readonly options: ClientOptions
    private readonly target: string


    /**
     * Creates a Client for calling the public and authenticated APIs of your Encore application.
     *
     * @param target  The target which the client should be configured to use. See Local and Environment for options.
     * @param options Options for the client
     */
    constructor(target: BaseURL, options?: ClientOptions) {
        this.target = target
        this.options = options ?? {}
        const base = new BaseClient(this.target, this.options)
        this.ai = new ai.ServiceClient(base)
        this.auth = new auth.ServiceClient(base)
        this.bookings = new bookings.ServiceClient(base)
        this.conversations = new conversations.ServiceClient(base)
        this.crm = new crm.ServiceClient(base)
        this.files = new files.ServiceClient(base)
        this.fleet = new fleet.ServiceClient(base)
        this.quotes = new quotes.ServiceClient(base)
        this.settings = new settings.ServiceClient(base)
    }

    /**
     * Creates a new Encore client with the given client options set.
     *
     * @param options Client options to set. They are merged with existing options.
     **/
    public with(options: ClientOptions): Client {
        return new Client(this.target, {
            ...this.options,
            ...options,
        })
    }
}

/**
 * Import the auth handler to be able to derive the auth type
 */
import type { auth as auth_auth } from "~backend/auth/auth";

/**
 * ClientOptions allows you to override any default behaviour within the generated Encore client.
 */
export interface ClientOptions {
    /**
     * By default the client will use the inbuilt fetch function for making the API requests.
     * however you can override it with your own implementation here if you want to run custom
     * code on each API request made or response received.
     */
    fetcher?: Fetcher

    /** Default RequestInit to be used for the client */
    requestInit?: Omit<RequestInit, "headers"> & { headers?: Record<string, string> }

    /**
     * Allows you to set the authentication data to be used for each
     * request either by passing in a static object or by passing in
     * a function which returns a new object for each request.
     */
    auth?: RequestType<typeof auth_auth> | AuthDataGenerator
}

/**
 * Import the endpoint handlers to derive the types for the client.
 */
import {
    getUsageStats as api_ai_assistant_getUsageStats,
    queryAssistant as api_ai_assistant_queryAssistant
} from "~backend/ai/assistant";

export namespace ai {

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.getUsageStats = this.getUsageStats.bind(this)
            this.queryAssistant = this.queryAssistant.bind(this)
        }

        public async getUsageStats(): Promise<ResponseType<typeof api_ai_assistant_getUsageStats>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/ai/usage`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_ai_assistant_getUsageStats>
        }

        public async queryAssistant(params: RequestType<typeof api_ai_assistant_queryAssistant>): Promise<ResponseType<typeof api_ai_assistant_queryAssistant>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/ai/query`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_ai_assistant_queryAssistant>
        }
    }
}

/**
 * Import the endpoint handlers to derive the types for the client.
 */
import { me as api_auth_me_me } from "~backend/auth/me";

export namespace auth {

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.me = this.me.bind(this)
        }

        public async me(): Promise<ResponseType<typeof api_auth_me_me>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/me`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_auth_me_me>
        }
    }
}

/**
 * Import the endpoint handlers to derive the types for the client.
 */
import {
    listBookings as api_bookings_bookings_listBookings,
    quickBook as api_bookings_bookings_quickBook
} from "~backend/bookings/bookings";

export namespace bookings {

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.listBookings = this.listBookings.bind(this)
            this.quickBook = this.quickBook.bind(this)
        }

        public async listBookings(): Promise<ResponseType<typeof api_bookings_bookings_listBookings>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/bookings`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_bookings_bookings_listBookings>
        }

        public async quickBook(params: RequestType<typeof api_bookings_bookings_quickBook>): Promise<ResponseType<typeof api_bookings_bookings_quickBook>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/bookings/quick`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_bookings_bookings_quickBook>
        }
    }
}

/**
 * Import the endpoint handlers to derive the types for the client.
 */
import {
    getThreadMessages as api_conversations_conversations_getThreadMessages,
    inboundWebhook as api_conversations_conversations_inboundWebhook,
    listThreads as api_conversations_conversations_listThreads,
    sendMessage as api_conversations_conversations_sendMessage
} from "~backend/conversations/conversations";

export namespace conversations {

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.getThreadMessages = this.getThreadMessages.bind(this)
            this.inboundWebhook = this.inboundWebhook.bind(this)
            this.listThreads = this.listThreads.bind(this)
            this.sendMessage = this.sendMessage.bind(this)
        }

        public async getThreadMessages(params: { threadId: string }): Promise<ResponseType<typeof api_conversations_conversations_getThreadMessages>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/conversations/${encodeURIComponent(params.threadId)}/messages`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_conversations_conversations_getThreadMessages>
        }

        public async inboundWebhook(params: RequestType<typeof api_conversations_conversations_inboundWebhook>): Promise<ResponseType<typeof api_conversations_conversations_inboundWebhook>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/conversations/webhook`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_conversations_conversations_inboundWebhook>
        }

        public async listThreads(): Promise<ResponseType<typeof api_conversations_conversations_listThreads>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/conversations`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_conversations_conversations_listThreads>
        }

        public async sendMessage(params: RequestType<typeof api_conversations_conversations_sendMessage>): Promise<ResponseType<typeof api_conversations_conversations_sendMessage>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/conversations/send`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_conversations_conversations_sendMessage>
        }
    }
}

/**
 * Import the endpoint handlers to derive the types for the client.
 */
import {
    getMessages as api_crm_communications_getMessages,
    markAsRead as api_crm_communications_markAsRead,
    sendMessage as api_crm_communications_sendMessage
} from "~backend/crm/communications";
import {
    createLead as api_crm_leads_createLead,
    getDashboardMetrics as api_crm_leads_getDashboardMetrics,
    getLeads as api_crm_leads_getLeads,
    updateLead as api_crm_leads_updateLead
} from "~backend/crm/leads";

export namespace crm {

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.createLead = this.createLead.bind(this)
            this.getDashboardMetrics = this.getDashboardMetrics.bind(this)
            this.getLeads = this.getLeads.bind(this)
            this.getMessages = this.getMessages.bind(this)
            this.markAsRead = this.markAsRead.bind(this)
            this.sendMessage = this.sendMessage.bind(this)
            this.updateLead = this.updateLead.bind(this)
        }

        public async createLead(params: RequestType<typeof api_crm_leads_createLead>): Promise<ResponseType<typeof api_crm_leads_createLead>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/leads`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_crm_leads_createLead>
        }

        public async getDashboardMetrics(): Promise<ResponseType<typeof api_crm_leads_getDashboardMetrics>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/dashboard/metrics`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_crm_leads_getDashboardMetrics>
        }

        public async getLeads(): Promise<ResponseType<typeof api_crm_leads_getLeads>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/leads`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_crm_leads_getLeads>
        }

        public async getMessages(params: { lead_id: number }): Promise<ResponseType<typeof api_crm_communications_getMessages>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/leads/${encodeURIComponent(params.lead_id)}/messages`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_crm_communications_getMessages>
        }

        public async markAsRead(params: { lead_id: number }): Promise<void> {
            await this.baseClient.callTypedAPI(`/leads/${encodeURIComponent(params.lead_id)}/messages/read`, {method: "PUT", body: undefined})
        }

        public async sendMessage(params: RequestType<typeof api_crm_communications_sendMessage>): Promise<ResponseType<typeof api_crm_communications_sendMessage>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/messages`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_crm_communications_sendMessage>
        }

        public async updateLead(params: RequestType<typeof api_crm_leads_updateLead>): Promise<ResponseType<typeof api_crm_leads_updateLead>> {
            // Construct the body with only the fields which we want encoded within the body (excluding query string or header fields)
            const body: Record<string, any> = {
                "booking_date": params["booking_date"],
                budget:         params.budget,
                email:          params.email,
                name:           params.name,
                notes:          params.notes,
                "party_size":   params["party_size"],
                phone:          params.phone,
                priority:       params.priority,
                status:         params.status,
                "vessel_type":  params["vessel_type"],
            }

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/leads/${encodeURIComponent(params.id)}`, {method: "PUT", body: JSON.stringify(body)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_crm_leads_updateLead>
        }
    }
}

/**
 * Import the endpoint handlers to derive the types for the client.
 */
import {
    deleteFile as api_files_files_deleteFile,
    getFileUrl as api_files_files_getFileUrl,
    getUploadUrl as api_files_files_getUploadUrl,
    listFiles as api_files_files_listFiles,
    setPrimaryFile as api_files_files_setPrimaryFile
} from "~backend/files/files";

export namespace files {

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.deleteFile = this.deleteFile.bind(this)
            this.getFileUrl = this.getFileUrl.bind(this)
            this.getUploadUrl = this.getUploadUrl.bind(this)
            this.listFiles = this.listFiles.bind(this)
            this.setPrimaryFile = this.setPrimaryFile.bind(this)
        }

        public async deleteFile(params: { fileId: string }): Promise<ResponseType<typeof api_files_files_deleteFile>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/files/${encodeURIComponent(params.fileId)}`, {method: "DELETE", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_files_files_deleteFile>
        }

        public async getFileUrl(params: { fileId: string }): Promise<ResponseType<typeof api_files_files_getFileUrl>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/files/${encodeURIComponent(params.fileId)}/url`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_files_files_getFileUrl>
        }

        public async getUploadUrl(params: RequestType<typeof api_files_files_getUploadUrl>): Promise<ResponseType<typeof api_files_files_getUploadUrl>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/files/upload-url`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_files_files_getUploadUrl>
        }

        public async listFiles(params: RequestType<typeof api_files_files_listFiles>): Promise<ResponseType<typeof api_files_files_listFiles>> {
            // Convert our params into the objects we need for the request
            const query = makeRecord<string, string | string[]>({
                ownerId:   params.ownerId,
                ownerType: params.ownerType,
            })

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/files`, {query, method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_files_files_listFiles>
        }

        public async setPrimaryFile(params: { fileId: string }): Promise<ResponseType<typeof api_files_files_setPrimaryFile>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/files/${encodeURIComponent(params.fileId)}/primary`, {method: "POST", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_files_files_setPrimaryFile>
        }
    }
}

/**
 * Import the endpoint handlers to derive the types for the client.
 */
import {
    createService as api_fleet_services_createService,
    listServices as api_fleet_services_listServices,
    updateService as api_fleet_services_updateService
} from "~backend/fleet/services";
import {
    createShip as api_fleet_ships_createShip,
    listShips as api_fleet_ships_listShips,
    updateShip as api_fleet_ships_updateShip,
    updateShipStatus as api_fleet_ships_updateShipStatus
} from "~backend/fleet/ships";

export namespace fleet {

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.createService = this.createService.bind(this)
            this.createShip = this.createShip.bind(this)
            this.listServices = this.listServices.bind(this)
            this.listShips = this.listShips.bind(this)
            this.updateService = this.updateService.bind(this)
            this.updateShip = this.updateShip.bind(this)
            this.updateShipStatus = this.updateShipStatus.bind(this)
        }

        public async createService(params: RequestType<typeof api_fleet_services_createService>): Promise<ResponseType<typeof api_fleet_services_createService>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/services`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_fleet_services_createService>
        }

        public async createShip(params: RequestType<typeof api_fleet_ships_createShip>): Promise<ResponseType<typeof api_fleet_ships_createShip>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/ships`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_fleet_ships_createShip>
        }

        public async listServices(): Promise<ResponseType<typeof api_fleet_services_listServices>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/services`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_fleet_services_listServices>
        }

        public async listShips(): Promise<ResponseType<typeof api_fleet_ships_listShips>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/ships`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_fleet_ships_listShips>
        }

        public async updateService(params: RequestType<typeof api_fleet_services_updateService>): Promise<ResponseType<typeof api_fleet_services_updateService>> {
            // Construct the body with only the fields which we want encoded within the body (excluding query string or header fields)
            const body: Record<string, any> = {
                defaultQuantity: params.defaultQuantity,
                description:     params.description,
                name:            params.name,
                published:       params.published,
                unitPrice:       params.unitPrice,
                unitType:        params.unitType,
            }

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/services/${encodeURIComponent(params.id)}`, {method: "PUT", body: JSON.stringify(body)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_fleet_services_updateService>
        }

        public async updateShip(params: RequestType<typeof api_fleet_ships_updateShip>): Promise<ResponseType<typeof api_fleet_ships_updateShip>> {
            // Construct the body with only the fields which we want encoded within the body (excluding query string or header fields)
            const body: Record<string, any> = {
                capacity:    params.capacity,
                description: params.description,
                hourlyRate:  params.hourlyRate,
                images:      params.images,
                name:        params.name,
                published:   params.published,
            }

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/ships/${encodeURIComponent(params.id)}`, {method: "PUT", body: JSON.stringify(body)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_fleet_ships_updateShip>
        }

        public async updateShipStatus(params: RequestType<typeof api_fleet_ships_updateShipStatus>): Promise<ResponseType<typeof api_fleet_ships_updateShipStatus>> {
            // Construct the body with only the fields which we want encoded within the body (excluding query string or header fields)
            const body: Record<string, any> = {
                status:       params.status,
                statusEnd:    params.statusEnd,
                statusReason: params.statusReason,
                statusStart:  params.statusStart,
            }

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/ships/${encodeURIComponent(params.id)}/status`, {method: "POST", body: JSON.stringify(body)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_fleet_ships_updateShipStatus>
        }
    }
}

/**
 * Import the endpoint handlers to derive the types for the client.
 */
import { calculateQuote as api_quotes_calculator_calculateQuote } from "~backend/quotes/calculator";
import {
    createPricingRule as api_quotes_pricing_rules_createPricingRule,
    listPricingRules as api_quotes_pricing_rules_listPricingRules,
    updatePricingRule as api_quotes_pricing_rules_updatePricingRule
} from "~backend/quotes/pricing_rules";
import {
    createQuote as api_quotes_quotes_createQuote,
    listQuotes as api_quotes_quotes_listQuotes
} from "~backend/quotes/quotes";

export namespace quotes {

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.calculateQuote = this.calculateQuote.bind(this)
            this.createPricingRule = this.createPricingRule.bind(this)
            this.createQuote = this.createQuote.bind(this)
            this.listPricingRules = this.listPricingRules.bind(this)
            this.listQuotes = this.listQuotes.bind(this)
            this.updatePricingRule = this.updatePricingRule.bind(this)
        }

        public async calculateQuote(params: RequestType<typeof api_quotes_calculator_calculateQuote>): Promise<ResponseType<typeof api_quotes_calculator_calculateQuote>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/quotes/calc`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_quotes_calculator_calculateQuote>
        }

        public async createPricingRule(params: RequestType<typeof api_quotes_pricing_rules_createPricingRule>): Promise<ResponseType<typeof api_quotes_pricing_rules_createPricingRule>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/pricing-rules`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_quotes_pricing_rules_createPricingRule>
        }

        public async createQuote(params: RequestType<typeof api_quotes_quotes_createQuote>): Promise<ResponseType<typeof api_quotes_quotes_createQuote>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/quotes`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_quotes_quotes_createQuote>
        }

        public async listPricingRules(): Promise<ResponseType<typeof api_quotes_pricing_rules_listPricingRules>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/pricing-rules`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_quotes_pricing_rules_listPricingRules>
        }

        public async listQuotes(): Promise<ResponseType<typeof api_quotes_quotes_listQuotes>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/quotes`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_quotes_quotes_listQuotes>
        }

        public async updatePricingRule(params: RequestType<typeof api_quotes_pricing_rules_updatePricingRule>): Promise<ResponseType<typeof api_quotes_pricing_rules_updatePricingRule>> {
            // Construct the body with only the fields which we want encoded within the body (excluding query string or header fields)
            const body: Record<string, any> = {
                action:    params.action,
                condition: params.condition,
                name:      params.name,
                priority:  params.priority,
                published: params.published,
            }

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/pricing-rules/${encodeURIComponent(params.id)}`, {method: "PUT", body: JSON.stringify(body)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_quotes_pricing_rules_updatePricingRule>
        }
    }
}

/**
 * Import the endpoint handlers to derive the types for the client.
 */
import {
    getSettings as api_settings_settings_getSettings,
    updateSettings as api_settings_settings_updateSettings
} from "~backend/settings/settings";

export namespace settings {

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.getSettings = this.getSettings.bind(this)
            this.updateSettings = this.updateSettings.bind(this)
        }

        public async getSettings(): Promise<ResponseType<typeof api_settings_settings_getSettings>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/settings`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_settings_settings_getSettings>
        }

        public async updateSettings(params: RequestType<typeof api_settings_settings_updateSettings>): Promise<ResponseType<typeof api_settings_settings_updateSettings>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/settings`, {method: "PATCH", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_settings_settings_updateSettings>
        }
    }
}


type PickMethods<Type> = Omit<CallParameters, "method"> & { method?: Type };

// Helper type to omit all fields that are cookies.
type OmitCookie<T> = {
  [K in keyof T as T[K] extends CookieWithOptions<any> ? never : K]: T[K];
};

type RequestType<Type extends (...args: any[]) => any> =
  Parameters<Type> extends [infer H, ...any[]]
    ? OmitCookie<H>
    : void;

type ResponseType<Type extends (...args: any[]) => any> = OmitCookie<Awaited<ReturnType<Type>>>;

function dateReviver(key: string, value: any): any {
  if (
    typeof value === "string" &&
    value.length >= 10 &&
    value.charCodeAt(0) >= 48 && // '0'
    value.charCodeAt(0) <= 57 // '9'
  ) {
    const parsedDate = new Date(value);
    if (!isNaN(parsedDate.getTime())) {
      return parsedDate;
    }
  }
  return value;
}


function encodeQuery(parts: Record<string, string | string[]>): string {
    const pairs: string[] = []
    for (const key in parts) {
        const val = (Array.isArray(parts[key]) ?  parts[key] : [parts[key]]) as string[]
        for (const v of val) {
            pairs.push(`${key}=${encodeURIComponent(v)}`)
        }
    }
    return pairs.join("&")
}

// makeRecord takes a record and strips any undefined values from it,
// and returns the same record with a narrower type.
// @ts-ignore - TS ignore because makeRecord is not always used
function makeRecord<K extends string | number | symbol, V>(record: Record<K, V | undefined>): Record<K, V> {
    for (const key in record) {
        if (record[key] === undefined) {
            delete record[key]
        }
    }
    return record as Record<K, V>
}

import {
  StreamInOutHandlerFn,
  StreamInHandlerFn,
  StreamOutHandlerFn,
} from "encore.dev/api";

type StreamRequest<Type> = Type extends
  | StreamInOutHandlerFn<any, infer Req, any>
  | StreamInHandlerFn<any, infer Req, any>
  | StreamOutHandlerFn<any, any>
  ? Req
  : never;

type StreamResponse<Type> = Type extends
  | StreamInOutHandlerFn<any, any, infer Resp>
  | StreamInHandlerFn<any, any, infer Resp>
  | StreamOutHandlerFn<any, infer Resp>
  ? Resp
  : never;


function encodeWebSocketHeaders(headers: Record<string, string>) {
    // url safe, no pad
    const base64encoded = btoa(JSON.stringify(headers))
      .replaceAll("=", "")
      .replaceAll("+", "-")
      .replaceAll("/", "_");
    return "encore.dev.headers." + base64encoded;
}

class WebSocketConnection {
    public ws: WebSocket;

    private hasUpdateHandlers: (() => void)[] = [];

    constructor(url: string, headers?: Record<string, string>) {
        let protocols = ["encore-ws"];
        if (headers) {
            protocols.push(encodeWebSocketHeaders(headers))
        }

        this.ws = new WebSocket(url, protocols)

        this.on("error", () => {
            this.resolveHasUpdateHandlers();
        });

        this.on("close", () => {
            this.resolveHasUpdateHandlers();
        });
    }

    resolveHasUpdateHandlers() {
        const handlers = this.hasUpdateHandlers;
        this.hasUpdateHandlers = [];

        for (const handler of handlers) {
            handler()
        }
    }

    async hasUpdate() {
        // await until a new message have been received, or the socket is closed
        await new Promise((resolve) => {
            this.hasUpdateHandlers.push(() => resolve(null))
        });
    }

    on(type: "error" | "close" | "message" | "open", handler: (event: any) => void) {
        this.ws.addEventListener(type, handler);
    }

    off(type: "error" | "close" | "message" | "open", handler: (event: any) => void) {
        this.ws.removeEventListener(type, handler);
    }

    close() {
        this.ws.close();
    }
}

export class StreamInOut<Request, Response> {
    public socket: WebSocketConnection;
    private buffer: Response[] = [];

    constructor(url: string, headers?: Record<string, string>) {
        this.socket = new WebSocketConnection(url, headers);
        this.socket.on("message", (event: any) => {
            this.buffer.push(JSON.parse(event.data, dateReviver));
            this.socket.resolveHasUpdateHandlers();
        });
    }

    close() {
        this.socket.close();
    }

    async send(msg: Request) {
        if (this.socket.ws.readyState === WebSocket.CONNECTING) {
            // await that the socket is opened
            await new Promise((resolve) => {
                this.socket.ws.addEventListener("open", resolve, { once: true });
            });
        }

        return this.socket.ws.send(JSON.stringify(msg));
    }

    async next(): Promise<Response | undefined> {
        for await (const next of this) return next;
        return undefined;
    }

    async *[Symbol.asyncIterator](): AsyncGenerator<Response, undefined, void> {
        while (true) {
            if (this.buffer.length > 0) {
                yield this.buffer.shift() as Response;
            } else {
                if (this.socket.ws.readyState === WebSocket.CLOSED) return;
                await this.socket.hasUpdate();
            }
        }
    }
}

export class StreamIn<Response> {
    public socket: WebSocketConnection;
    private buffer: Response[] = [];

    constructor(url: string, headers?: Record<string, string>) {
        this.socket = new WebSocketConnection(url, headers);
        this.socket.on("message", (event: any) => {
            this.buffer.push(JSON.parse(event.data, dateReviver));
            this.socket.resolveHasUpdateHandlers();
        });
    }

    close() {
        this.socket.close();
    }

    async next(): Promise<Response | undefined> {
        for await (const next of this) return next;
        return undefined;
    }

    async *[Symbol.asyncIterator](): AsyncGenerator<Response, undefined, void> {
        while (true) {
            if (this.buffer.length > 0) {
                yield this.buffer.shift() as Response;
            } else {
                if (this.socket.ws.readyState === WebSocket.CLOSED) return;
                await this.socket.hasUpdate();
            }
        }
    }
}

export class StreamOut<Request, Response> {
    public socket: WebSocketConnection;
    private responseValue: Promise<Response>;

    constructor(url: string, headers?: Record<string, string>) {
        let responseResolver: (_: any) => void;
        this.responseValue = new Promise((resolve) => responseResolver = resolve);

        this.socket = new WebSocketConnection(url, headers);
        this.socket.on("message", (event: any) => {
            responseResolver(JSON.parse(event.data, dateReviver))
        });
    }

    async response(): Promise<Response> {
        return this.responseValue;
    }

    close() {
        this.socket.close();
    }

    async send(msg: Request) {
        if (this.socket.ws.readyState === WebSocket.CONNECTING) {
            // await that the socket is opened
            await new Promise((resolve) => {
                this.socket.ws.addEventListener("open", resolve, { once: true });
            });
        }

        return this.socket.ws.send(JSON.stringify(msg));
    }
}
// CallParameters is the type of the parameters to a method call, but require headers to be a Record type
type CallParameters = Omit<RequestInit, "headers"> & {
    /** Headers to be sent with the request */
    headers?: Record<string, string>

    /** Query parameters to be sent with the request */
    query?: Record<string, string | string[]>
}

// AuthDataGenerator is a function that returns a new instance of the authentication data required by this API
export type AuthDataGenerator = () =>
  | RequestType<typeof auth_auth>
  | Promise<RequestType<typeof auth_auth> | undefined>
  | undefined;

// A fetcher is the prototype for the inbuilt Fetch function
export type Fetcher = typeof fetch;

const boundFetch = fetch.bind(this);

class BaseClient {
    readonly baseURL: string
    readonly fetcher: Fetcher
    readonly headers: Record<string, string>
    readonly requestInit: Omit<RequestInit, "headers"> & { headers?: Record<string, string> }
    readonly authGenerator?: AuthDataGenerator

    constructor(baseURL: string, options: ClientOptions) {
        this.baseURL = baseURL
        this.headers = {}

        // Add User-Agent header if the script is running in the server
        // because browsers do not allow setting User-Agent headers to requests
        if (!BROWSER) {
            this.headers["User-Agent"] = "-Generated-TS-Client (Encore/1.50.6)";
        }

        this.requestInit = options.requestInit ?? {};

        // Setup what fetch function we'll be using in the base client
        if (options.fetcher !== undefined) {
            this.fetcher = options.fetcher
        } else {
            this.fetcher = boundFetch
        }

        // Setup an authentication data generator using the auth data token option
        if (options.auth !== undefined) {
            const auth = options.auth
            if (typeof auth === "function") {
                this.authGenerator = auth
            } else {
                this.authGenerator = () => auth
            }
        }
    }

    async getAuthData(): Promise<CallParameters | undefined> {
        let authData: RequestType<typeof auth_auth> | undefined;

        // If authorization data generator is present, call it and add the returned data to the request
        if (this.authGenerator) {
            const mayBePromise = this.authGenerator();
            if (mayBePromise instanceof Promise) {
                authData = await mayBePromise;
            } else {
                authData = mayBePromise;
            }
        }

        if (authData) {
            const data: CallParameters = {};

            data.headers = makeRecord<string, string>({
                authorization: authData.authorization,
            });

            return data;
        }

        return undefined;
    }

    // createStreamInOut sets up a stream to a streaming API endpoint.
    async createStreamInOut<Request, Response>(path: string, params?: CallParameters): Promise<StreamInOut<Request, Response>> {
        let { query, headers } = params ?? {};

        // Fetch auth data if there is any
        const authData = await this.getAuthData();

        // If we now have authentication data, add it to the request
        if (authData) {
            if (authData.query) {
                query = {...query, ...authData.query};
            }
            if (authData.headers) {
                headers = {...headers, ...authData.headers};
            }
        }

        const queryString = query ? '?' + encodeQuery(query) : ''
        return new StreamInOut(this.baseURL + path + queryString, headers);
    }

    // createStreamIn sets up a stream to a streaming API endpoint.
    async createStreamIn<Response>(path: string, params?: CallParameters): Promise<StreamIn<Response>> {
        let { query, headers } = params ?? {};

        // Fetch auth data if there is any
        const authData = await this.getAuthData();

        // If we now have authentication data, add it to the request
        if (authData) {
            if (authData.query) {
                query = {...query, ...authData.query};
            }
            if (authData.headers) {
                headers = {...headers, ...authData.headers};
            }
        }

        const queryString = query ? '?' + encodeQuery(query) : ''
        return new StreamIn(this.baseURL + path + queryString, headers);
    }

    // createStreamOut sets up a stream to a streaming API endpoint.
    async createStreamOut<Request, Response>(path: string, params?: CallParameters): Promise<StreamOut<Request, Response>> {
        let { query, headers } = params ?? {};

        // Fetch auth data if there is any
        const authData = await this.getAuthData();

        // If we now have authentication data, add it to the request
        if (authData) {
            if (authData.query) {
                query = {...query, ...authData.query};
            }
            if (authData.headers) {
                headers = {...headers, ...authData.headers};
            }
        }

        const queryString = query ? '?' + encodeQuery(query) : ''
        return new StreamOut(this.baseURL + path + queryString, headers);
    }

    // callTypedAPI makes an API call, defaulting content type to "application/json"
    public async callTypedAPI(path: string, params?: CallParameters): Promise<Response> {
        return this.callAPI(path, {
            ...params,
            headers: { "Content-Type": "application/json", ...params?.headers }
        });
    }

    // callAPI is used by each generated API method to actually make the request
    public async callAPI(path: string, params?: CallParameters): Promise<Response> {
        let { query, headers, ...rest } = params ?? {}
        const init = {
            ...this.requestInit,
            ...rest,
        }

        // Merge our headers with any predefined headers
        init.headers = {...this.headers, ...init.headers, ...headers}

        // Fetch auth data if there is any
        const authData = await this.getAuthData();

        // If we now have authentication data, add it to the request
        if (authData) {
            if (authData.query) {
                query = {...query, ...authData.query};
            }
            if (authData.headers) {
                init.headers = {...init.headers, ...authData.headers};
            }
        }

        // Make the actual request
        const queryString = query ? '?' + encodeQuery(query) : ''
        const response = await this.fetcher(this.baseURL+path+queryString, init)

        // handle any error responses
        if (!response.ok) {
            // try and get the error message from the response body
            let body: APIErrorResponse = { code: ErrCode.Unknown, message: `request failed: status ${response.status}` }

            // if we can get the structured error we should, otherwise give a best effort
            try {
                const text = await response.text()

                try {
                    const jsonBody = JSON.parse(text)
                    if (isAPIErrorResponse(jsonBody)) {
                        body = jsonBody
                    } else {
                        body.message += ": " + JSON.stringify(jsonBody)
                    }
                } catch {
                    body.message += ": " + text
                }
            } catch (e) {
                // otherwise we just append the text to the error message
                body.message += ": " + String(e)
            }

            throw new APIError(response.status, body)
        }

        return response
    }
}

/**
 * APIErrorDetails represents the response from an Encore API in the case of an error
 */
interface APIErrorResponse {
    code: ErrCode
    message: string
    details?: any
}

function isAPIErrorResponse(err: any): err is APIErrorResponse {
    return (
        err !== undefined && err !== null &&
        isErrCode(err.code) &&
        typeof(err.message) === "string" &&
        (err.details === undefined || err.details === null || typeof(err.details) === "object")
    )
}

function isErrCode(code: any): code is ErrCode {
    return code !== undefined && Object.values(ErrCode).includes(code)
}

/**
 * APIError represents a structured error as returned from an Encore application.
 */
export class APIError extends Error {
    /**
     * The HTTP status code associated with the error.
     */
    public readonly status: number

    /**
     * The Encore error code
     */
    public readonly code: ErrCode

    /**
     * The error details
     */
    public readonly details?: any

    constructor(status: number, response: APIErrorResponse) {
        // extending errors causes issues after you construct them, unless you apply the following fixes
        super(response.message);

        // set error name as constructor name, make it not enumerable to keep native Error behavior
        // https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/new.target#new.target_in_constructors
        Object.defineProperty(this, 'name', {
            value:        'APIError',
            enumerable:   false,
            configurable: true,
        })

        // fix the prototype chain
        if ((Object as any).setPrototypeOf == undefined) {
            (this as any).__proto__ = APIError.prototype
        } else {
            Object.setPrototypeOf(this, APIError.prototype);
        }

        // capture a stack trace
        if ((Error as any).captureStackTrace !== undefined) {
            (Error as any).captureStackTrace(this, this.constructor);
        }

        this.status = status
        this.code = response.code
        this.details = response.details
    }
}

/**
 * Typeguard allowing use of an APIError's fields'
 */
export function isAPIError(err: any): err is APIError {
    return err instanceof APIError;
}

export enum ErrCode {
    /**
     * OK indicates the operation was successful.
     */
    OK = "ok",

    /**
     * Canceled indicates the operation was canceled (typically by the caller).
     *
     * Encore will generate this error code when cancellation is requested.
     */
    Canceled = "canceled",

    /**
     * Unknown error. An example of where this error may be returned is
     * if a Status value received from another address space belongs to
     * an error-space that is not known in this address space. Also
     * errors raised by APIs that do not return enough error information
     * may be converted to this error.
     *
     * Encore will generate this error code in the above two mentioned cases.
     */
    Unknown = "unknown",

    /**
     * InvalidArgument indicates client specified an invalid argument.
     * Note that this differs from FailedPrecondition. It indicates arguments
     * that are problematic regardless of the state of the system
     * (e.g., a malformed file name).
     *
     * This error code will not be generated by the gRPC framework.
     */
    InvalidArgument = "invalid_argument",

    /**
     * DeadlineExceeded means operation expired before completion.
     * For operations that change the state of the system, this error may be
     * returned even if the operation has completed successfully. For
     * example, a successful response from a server could have been delayed
     * long enough for the deadline to expire.
     *
     * The gRPC framework will generate this error code when the deadline is
     * exceeded.
     */
    DeadlineExceeded = "deadline_exceeded",

    /**
     * NotFound means some requested entity (e.g., file or directory) was
     * not found.
     *
     * This error code will not be generated by the gRPC framework.
     */
    NotFound = "not_found",

    /**
     * AlreadyExists means an attempt to create an entity failed because one
     * already exists.
     *
     * This error code will not be generated by the gRPC framework.
     */
    AlreadyExists = "already_exists",

    /**
     * PermissionDenied indicates the caller does not have permission to
     * execute the specified operation. It must not be used for rejections
     * caused by exhausting some resource (use ResourceExhausted
     * instead for those errors). It must not be
     * used if the caller cannot be identified (use Unauthenticated
     * instead for those errors).
     *
     * This error code will not be generated by the gRPC core framework,
     * but expect authentication middleware to use it.
     */
    PermissionDenied = "permission_denied",

    /**
     * ResourceExhausted indicates some resource has been exhausted, perhaps
     * a per-user quota, or perhaps the entire file system is out of space.
     *
     * This error code will be generated by the gRPC framework in
     * out-of-memory and server overload situations, or when a message is
     * larger than the configured maximum size.
     */
    ResourceExhausted = "resource_exhausted",

    /**
     * FailedPrecondition indicates operation was rejected because the
     * system is not in a state required for the operation's execution.
     * For example, directory to be deleted may be non-empty, an rmdir
     * operation is applied to a non-directory, etc.
     *
     * A litmus test that may help a service implementor in deciding
     * between FailedPrecondition, Aborted, and Unavailable:
     *  (a) Use Unavailable if the client can retry just the failing call.
     *  (b) Use Aborted if the client should retry at a higher-level
     *      (e.g., restarting a read-modify-write sequence).
     *  (c) Use FailedPrecondition if the client should not retry until
     *      the system state has been explicitly fixed. E.g., if an "rmdir"
     *      fails because the directory is non-empty, FailedPrecondition
     *      should be returned since the client should not retry unless
     *      they have first fixed up the directory by deleting files from it.
     *  (d) Use FailedPrecondition if the client performs conditional
     *      REST Get/Update/Delete on a resource and the resource on the
     *      server does not match the condition. E.g., conflicting
     *      read-modify-write on the same resource.
     *
     * This error code will not be generated by the gRPC framework.
     */
    FailedPrecondition = "failed_precondition",

    /**
     * Aborted indicates the operation was aborted, typically due to a
     * concurrency issue like sequencer check failures, transaction aborts,
     * etc.
     *
     * See litmus test above for deciding between FailedPrecondition,
     * Aborted, and Unavailable.
     */
    Aborted = "aborted",

    /**
     * OutOfRange means operation was attempted past the valid range.
     * E.g., seeking or reading past end of file.
     *
     * Unlike InvalidArgument, this error indicates a problem that may
     * be fixed if the system state changes. For example, a 32-bit file
     * system will generate InvalidArgument if asked to read at an
     * offset that is not in the range [0,2^32-1], but it will generate
     * OutOfRange if asked to read from an offset past the current
     * file size.
     *
     * There is a fair bit of overlap between FailedPrecondition and
     * OutOfRange. We recommend using OutOfRange (the more specific
     * error) when it applies so that callers who are iterating through
     * a space can easily look for an OutOfRange error to detect when
     * they are done.
     *
     * This error code will not be generated by the gRPC framework.
     */
    OutOfRange = "out_of_range",

    /**
     * Unimplemented indicates operation is not implemented or not
     * supported/enabled in this service.
     *
     * This error code will be generated by the gRPC framework. Most
     * commonly, you will see this error code when a method implementation
     * is missing on the server. It can also be generated for unknown
     * compression algorithms or a disagreement as to whether an RPC should
     * be streaming.
     */
    Unimplemented = "unimplemented",

    /**
     * Internal errors. Means some invariants expected by underlying
     * system has been broken. If you see one of these errors,
     * something is very broken.
     *
     * This error code will be generated by the gRPC framework in several
     * internal error conditions.
     */
    Internal = "internal",

    /**
     * Unavailable indicates the service is currently unavailable.
     * This is a most likely a transient condition and may be corrected
     * by retrying with a backoff. Note that it is not always safe to retry
     * non-idempotent operations.
     *
     * See litmus test above for deciding between FailedPrecondition,
     * Aborted, and Unavailable.
     *
     * This error code will be generated by the gRPC framework during
     * abrupt shutdown of a server process or network connection.
     */
    Unavailable = "unavailable",

    /**
     * DataLoss indicates unrecoverable data loss or corruption.
     *
     * This error code will not be generated by the gRPC framework.
     */
    DataLoss = "data_loss",

    /**
     * Unauthenticated indicates the request does not have valid
     * authentication credentials for the operation.
     *
     * The gRPC framework will generate this error code when the
     * authentication metadata is invalid or a Credentials callback fails,
     * but also expect authentication middleware to generate it.
     */
    Unauthenticated = "unauthenticated",
}

export default new Client(import.meta.env.VITE_CLIENT_TARGET, { requestInit: { credentials: "include" } });
